import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const RESEND_KEY  = Deno.env.get("RESEND_API_KEY") ?? "";
const FROM        = Deno.env.get("RESEND_FROM") ?? "onboarding@resend.dev";

const supabaseAdmin = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
);

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });

  try {
    const { type, ...p } = await req.json();
    const lang = String(p.lang || "fr") === "en" ? "en" : "fr";
    let payload;

    if (type === "results") {
      const subject = lang === "en"
        ? `Results — ${p.exam_title}`
        : `Résultats — ${p.exam_title}`;
      payload = { from: FROM, to: [p.to_email], subject, html: resultsHtml(p, lang) };
    } else if (type === "retake") {
      const subject = lang === "en"
        ? `Exam link — ${p.exam_title}`
        : `Lien de reprise — ${p.exam_title}`;
      payload = { from: FROM, to: [p.to_email], subject, html: retakeHtml(p, lang) };
    } else if (type === "invite") {
      const subject = lang === "en"
        ? `Exam invitation — ${p.exam_title}`
        : `Invitation à l'examen — ${p.exam_title}`;
      payload = { from: FROM, to: [p.to_email], subject, html: inviteHtml(p, lang) };
      if (p.reply_to) payload.reply_to = p.reply_to;
    } else if (type === "ticket") {
      payload = {
        from: FROM,
        to: [p.to_email as string],
        subject: String(p.subject || `New ticket from ${p.teacher_name}`),
        html: ticketHtml(p as Record<string, string>),
      };
    } else {
      return respond({ error: "Unknown type" }, 400);
    }

    const r = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    const data = await r.json();

    if (r.ok) {
      // Fire-and-forget log — never block the response
      supabaseAdmin.from("email_logs").insert({
        type,
        to_email:   p.to_email   || null,
        exam_id:    p.exam_id    || null,
        attempt_id: p.attempt_id || null,
        teacher_id: p.teacher_id || null,
        resend_id:  data.id      || null,
        status:     "sent",
      }).then(() => {}).catch(() => {});
    }

    return respond(r.ok ? { id: data.id } : { error: data }, r.ok ? 200 : r.status);
  } catch (e) {
    return respond({ error: String(e) }, 500);
  }
});

function respond(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });
}

// ── Shared shell ──────────────────────────────────────────────────────────────

function emailShell(content: string, lang: string) {
  const footer = lang === "en"
    ? "This message was automatically generated by testflo."
    : "Ce message a été généré automatiquement par testflo.";
  return `<!DOCTYPE html>
<html lang="${lang}"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="font-family:Arial,sans-serif;background:#f1f5f9;margin:0;padding:32px 16px;">
<div style="max-width:600px;margin:0 auto;">
  <div style="background:#0f172a;padding:24px 32px;">
    <span style="font-family:Inter,Arial,sans-serif;font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.02em;">testflo</span>
  </div>
  ${content}
  <div style="padding:20px 0;text-align:center;font-size:11px;color:#94a3b8;">
    ${footer}
  </div>
</div>
</body></html>`;
}

// ── Strip HTML (Quill output) ─────────────────────────────────────────────────

function stripHtml(html: string): string {
  return (html || '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<li>/gi, '• ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// ── Results email ─────────────────────────────────────────────────────────────

function resultsHtml(p: Record<string, unknown>, lang: string) {
  const studentName   = String(p.student_name  || p.to_name || '');
  const examTitle     = String(p.exam_title    || '');
  const institution   = String(p.institution_name || '');
  const dateTaken     = String(p.date_taken    || '—');
  const scoreObtained = String(p.score_obtained ?? '—');
  const scoreTotal    = String(p.score_total   ?? '—');
  const scoreConverted = p.score_converted ? String(p.score_converted) : null;
  const teacherName   = String(p.teacher_name  || '');
  const teacherEmail  = String(p.teacher_email || '');
  const toEmail       = String(p.to_email      || '');

  const questions  = Array.isArray(p.questions) ? p.questions as Record<string, unknown>[] : null;
  const resultsUrl = p.results_url ? String(p.results_url) : null;

  // ── i18n strings ──────────────────────────────────────────────────────────
  const T = lang === "en" ? {
    scoreTotal:    "Total Score",
    date:          "Date",
    submittedOn:   "Submitted on",
    mcqHeader:     "Multiple choice questions",
    openHeader:    "Written questions",
    colQuestion:   "Question",
    colStudentAns: "Student answer",
    colCorrectAns: "Correct answer",
    colResult:     "Result",
    colQAndMore:   "Question · Response · Comment · Score",
    openResponse:  "Response",
    openComment:   "Teacher comment",
    openScore:     "Score",
  } : {
    scoreTotal:    "Score Total",
    date:          "Date",
    submittedOn:   "Soumis le",
    mcqHeader:     "Questions à choix multiple",
    openHeader:    "Questions rédigées",
    colQuestion:   "Question",
    colStudentAns: "Réponse candidat",
    colCorrectAns: "Bonne réponse",
    colResult:     "Résultat",
    colQAndMore:   "Question · Réponse · Commentaire · Note",
    openResponse:  "Réponse",
    openComment:   "Commentaire de l'enseignant",
    openScore:     "Note",
  };

  // ── Header stripe ─────────────────────────────────────────────────────────
  const headerStripe = `
  <div style="background:#fff;padding:24px 32px 20px;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">
    ${institution ? `<p style="margin:0 0 2px;font-size:0.68rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#94a3b8;">${esc(institution)}</p>` : ''}
    <h2 style="margin:0 0 8px;font-size:1.15rem;font-weight:700;color:#0a0a0a;line-height:1.3;">${esc(examTitle)}</h2>
    <p style="margin:0;font-size:0.85rem;color:#475569;"><strong>${esc(studentName)}</strong></p>
    <p style="margin:4px 0 0;font-size:0.8rem;color:#94a3b8;">${T.submittedOn} ${esc(dateTaken)}${teacherName ? ` · ${esc(teacherName)}` : ''}</p>
  </div>`;

  // ── Hero stats row ────────────────────────────────────────────────────────
  const pct = scoreTotal !== '0' && scoreTotal !== '—'
    ? Math.round((parseFloat(scoreObtained) / parseFloat(scoreTotal)) * 100)
    : null;

  const heroStats = `
  <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#fff;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;margin-bottom:0;">
    <tr>
      <td style="padding:20px 24px;border-right:1px solid #e2e8f0;vertical-align:top;width:50%;">
        <p style="margin:0 0 4px;font-size:0.6rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#94a3b8;">${T.scoreTotal}</p>
        <p style="margin:0;font-size:2rem;font-weight:700;color:#0a0a0a;line-height:1;">${esc(scoreObtained)} / ${esc(scoreTotal)}</p>
      </td>
      <td style="padding:20px 24px;vertical-align:top;width:50%;">
        <p style="margin:0 0 4px;font-size:0.6rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#94a3b8;">${T.date}</p>
        <p style="margin:0;font-size:0.95rem;font-weight:600;color:#1e293b;">${esc(dateTaken)}</p>
        ${institution ? `<p style="margin:4px 0 0;font-size:0.78rem;color:#94a3b8;">${esc(institution)}</p>` : ''}
      </td>
    </tr>
  </table>`;

  // ── CTA button (results-by-link mode) ────────────────────────────────────
  let ctaBlock = '';
  if (resultsUrl) {
    const btnLabel = lang === 'en' ? 'View your results →' : 'Consulter mes résultats →';
    const btnNote  = lang === 'en'
      ? 'This link gives access to your personal results only.'
      : 'Ce lien donne accès à vos résultats personnels uniquement.';
    ctaBlock = `
  <div style="background:#fff;padding:28px 32px;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;text-align:center;">
    <a href="${esc(resultsUrl)}" style="display:inline-block;background:#0f172a;color:#fff;padding:14px 32px;text-decoration:none;font-weight:700;font-size:0.9rem;letter-spacing:0.01em;">${btnLabel}</a>
    <p style="margin:12px 0 0;font-size:0.75rem;color:#94a3b8;">${btnNote}</p>
  </div>`;
  }

  // ── Question table ────────────────────────────────────────────────────────
  let questionTable = '';
  if (!resultsUrl && questions && questions.length > 0) {
    // Pool filtering — pool_selection: { sectionId: [qIdx, ...] } keyed by section DB id
    const poolSel = p.pool_selection && typeof p.pool_selection === 'object'
      ? p.pool_selection as Record<string, number[]>
      : null;
    const poolActive = poolSel !== null && Object.keys(poolSel).length > 0;

    // Section grouping
    const hasSections = questions.some(q => q.type === 'section');

    // Helper to render a single MCQ row
    function renderMcqRow(q: Record<string, unknown>, rowIdx: number): string {
      const options     = Array.isArray(q.options) ? q.options as string[] : [];
      const correctIdx  = typeof q.correct_index === 'number' ? q.correct_index : -1;
      const studentIdx  = typeof q.student_answer === 'number' ? q.student_answer : -1;
      const isCorrect   = studentIdx !== -1 && studentIdx === correctIdx;
      const correctText = correctIdx >= 0 ? (stripHtml(String(options[correctIdx] ?? '')) || '—') : '—';
      const studentText = studentIdx >= 0 ? (stripHtml(String(options[studentIdx] ?? '')) || (lang === "en" ? "No answer" : "Sans réponse")) : (lang === "en" ? "No answer" : "Sans réponse");
      const rowBg       = rowIdx % 2 === 0 ? '#ffffff' : '#f8fafc';
      // FIX 3 — fallback to Q{position} when text is empty
      const pos = typeof q.position === 'number' ? q.position : (rowIdx + 1);
      const qText = stripHtml(String(q.text || q.question_text || '')) || `Q${pos}`;
      return `
      <tr style="background:${rowBg};">
        <td style="padding:10px 14px;font-size:0.78rem;color:#1e293b;border-bottom:1px solid #e2e8f0;vertical-align:top;max-width:220px;">${esc(qText)}</td>
        <td style="padding:10px 14px;font-size:0.78rem;border-bottom:1px solid #e2e8f0;vertical-align:top;${isCorrect ? 'color:#1e293b;' : 'color:#dc2626;font-weight:600;'}">${esc(studentText)}</td>
        <td style="padding:10px 14px;font-size:0.78rem;color:#1e293b;border-bottom:1px solid #e2e8f0;vertical-align:top;">${esc(correctText)}</td>
        <td style="padding:10px 14px;font-size:1rem;border-bottom:1px solid #e2e8f0;text-align:center;vertical-align:middle;${isCorrect ? 'color:#16a34a;' : 'color:#dc2626;'}">${isCorrect ? '✓' : '✗'}</td>
      </tr>`;
    }

    // Helper to render a single open question row
    function renderOpenRow(q: Record<string, unknown>, rowIdx: number): string {
      const scoreLabel = q.open_score != null
        ? `<p style="margin:8px 0 0;font-size:0.78rem;font-weight:700;color:#475569;">${T.openScore} : <strong>${q.open_score} / ${q.max_points ?? '?'}</strong></p>`
        : '';
      const strippedResponse = stripHtml(String(q.student_response || ''));
      const responseBlock = strippedResponse
        ? `<p style="margin:0 0 4px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;">${T.openResponse}</p>
           <p style="margin:0 0 10px;font-size:0.82rem;color:#475569;font-style:italic;white-space:pre-wrap;">${esc(strippedResponse)}</p>`
        : '';
      const commentBlock = q.comment
        ? `<p style="margin:0 0 4px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;">${T.openComment}</p>
           <p style="margin:0;font-size:0.82rem;color:#1e293b;">${esc(String(q.comment))}</p>`
        : '';
      const rowBg = rowIdx % 2 === 0 ? '#ffffff' : '#f8fafc';
      // FIX 3 — fallback to Q{position} when text is empty
      const pos = typeof q.position === 'number' ? q.position : (rowIdx + 1);
      const qText = stripHtml(String(q.text || q.question_text || '')) || `Q${pos}`;
      return `
      <tr style="background:${rowBg};">
        <td style="padding:14px;font-size:0.82rem;color:#1e293b;border-bottom:1px solid #e2e8f0;font-weight:600;vertical-align:top;width:40%;">${esc(qText)}</td>
        <td style="padding:14px;border-bottom:1px solid #e2e8f0;vertical-align:top;">
          ${responseBlock}${commentBlock}${scoreLabel}
        </td>
      </tr>`;
    }

    // Helper to wrap MCQ rows in a section block
    function wrapMcqBlock(rows: string, headerLabel: string): string {
      if (!rows) return '';
      return `
  <div style="margin-top:0;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">
    <div style="background:#0f172a;padding:12px 24px;">
      <p style="margin:0;font-size:0.65rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:rgba(255,255,255,0.85);">${headerLabel}</p>
    </div>
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
      <thead>
        <tr style="background:#f8fafc;">
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:40%;">${T.colQuestion}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:25%;">${T.colStudentAns}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:25%;">${T.colCorrectAns}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:center;border-bottom:1px solid #e2e8f0;width:10%;">${T.colResult}</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`;
    }

    // Helper to wrap open rows in a section block
    function wrapOpenBlock(rows: string, headerLabel: string): string {
      if (!rows) return '';
      return `
  <div style="margin-top:0;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">
    <div style="background:#0f172a;padding:12px 24px;">
      <p style="margin:0;font-size:0.65rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:rgba(255,255,255,0.85);">${headerLabel}</p>
    </div>
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
      <thead>
        <tr style="background:#f8fafc;">
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:40%;">${T.colQuestion}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;">${T.colQAndMore}</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`;
    }

    if (hasSections) {
      // Group by teacher-defined sections; track section ID for per-section pool filtering
      type SectionGroup = { title: string; sectionId: string | null; items: { q: Record<string, unknown>; globalIdx: number }[] };
      const groups: SectionGroup[] = [];
      let currentGroup: SectionGroup = { title: '', sectionId: null, items: [] };
      let globalQIdx = 0;

      for (const item of questions) {
        if (item.type === 'section') {
          if (currentGroup.items.length > 0 || currentGroup.title) {
            groups.push(currentGroup);
          }
          const sId = typeof item.id === 'string' ? item.id : null;
          currentGroup = { title: String(item.text || item.question_text || ''), sectionId: sId, items: [] };
        } else {
          const idx = typeof (item as Record<string, unknown>).idx === 'number'
            ? (item as Record<string, unknown>).idx as number
            : globalQIdx;
          // Section-aware pool filtering: only apply when this section has a pool entry.
          // Non-pool sections (no key in poolSel) are always included.
          const sectionDrawn = poolSel && currentGroup.sectionId ? poolSel[currentGroup.sectionId] : null;
          const include = sectionDrawn ? sectionDrawn.includes(idx) : true;
          if (include) {
            currentGroup.items.push({ q: item, globalIdx: idx });
          }
          globalQIdx++;
        }
      }
      if (currentGroup.items.length > 0 || currentGroup.title) {
        groups.push(currentGroup);
      }

      for (const group of groups) {
        if (group.items.length === 0) continue;
        const sectionHeaderHtml = group.title
          ? `<div style="background:#0f172a;padding:12px 24px;"><p style="margin:0;font-size:0.65rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:rgba(255,255,255,0.85);">${esc(group.title)}</p></div>`
          : '';

        const mcqItems  = group.items.filter(({ q }) => q.type === 'mcq');
        const openItems = group.items.filter(({ q }) => q.type === 'open');

        let mcqRowsHtml = '';
        mcqItems.forEach(({ q }, i) => { mcqRowsHtml += renderMcqRow(q, i); });

        let openRowsHtml = '';
        openItems.filter(({ q }) => q.student_response || q.comment || q.open_score != null)
          .forEach(({ q }, i) => { openRowsHtml += renderOpenRow(q, i); });

        if (mcqRowsHtml || openRowsHtml) {
          questionTable += `
  <div style="margin-top:0;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">
    ${sectionHeaderHtml}`;

          if (mcqRowsHtml) {
            questionTable += `
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
      <thead>
        <tr style="background:#f8fafc;">
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:40%;">${T.colQuestion}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:25%;">${T.colStudentAns}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:25%;">${T.colCorrectAns}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:center;border-bottom:1px solid #e2e8f0;width:10%;">${T.colResult}</th>
        </tr>
      </thead>
      <tbody>${mcqRowsHtml}</tbody>
    </table>`;
          }

          if (openRowsHtml) {
            if (mcqRowsHtml) {
              // divider between MCQ and open within same section
              questionTable += `<div style="border-top:1px solid #e2e8f0;"></div>`;
            }
            questionTable += `
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
      <thead>
        <tr style="background:#f8fafc;">
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;width:40%;">${T.colQuestion}</th>
          <th style="padding:10px 14px;font-size:0.62rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#94a3b8;text-align:left;border-bottom:1px solid #e2e8f0;">${T.colQAndMore}</th>
        </tr>
      </thead>
      <tbody>${openRowsHtml}</tbody>
    </table>`;
          }

          questionTable += `</div>`;
        }
      }

      if (poolActive) {
        const note = lang === 'en'
          ? 'Questions shown reflect the questions served to this student.'
          : 'Les questions affichées correspondent aux questions présentées à cet étudiant.';
        questionTable += `<div style="padding:8px 16px;font-size:0.72rem;color:#94a3b8;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">${note}</div>`;
      }
    } else {
      // No sections — pool_selection cannot apply without sections; render all questions
      const filteredQuestions = questions.filter(q => q.type !== 'section');

      const mcqQs  = filteredQuestions.filter(q => q.type === 'mcq');
      const openQs = filteredQuestions.filter(q => q.type === 'open');

      const mcqRows = mcqQs.map((q, i) => renderMcqRow(q, i)).join('');
      questionTable += wrapMcqBlock(mcqRows, T.mcqHeader);

      const openRows = openQs
        .filter(q => q.student_response || q.comment || q.open_score != null)
        .map((q, i) => renderOpenRow(q, i)).join('');
      questionTable += wrapOpenBlock(openRows, T.openHeader);

      if (poolActive && (mcqRows || openRows)) {
        const note = lang === 'en'
          ? 'Questions shown reflect the questions served to this student.'
          : 'Les questions affichées correspondent aux questions présentées à cet étudiant.';
        questionTable += `<div style="padding:8px 16px;font-size:0.72rem;color:#94a3b8;border-left:1px solid #e2e8f0;border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;">${note}</div>`;
      }
    }
  }

  const contactBlock = (teacherName || teacherEmail) ? `
  <div style="border-top:1px solid #e2e8f0;margin:24px 0 16px;"></div>
  <div style="text-align:center;font-size:0.85rem;color:#64748b;padding:0 32px 8px;">
    ${lang === 'en'
      ? 'For any question regarding your result, contact your instructor :'
      : 'Pour toute question concernant votre résultat, contactez votre enseignant :'}
    <br>
    ${teacherName ? `<span style="font-weight:700;color:#1e293b;">${esc(teacherName)}</span>` : ''}${teacherName && teacherEmail ? ' — ' : ''}${teacherEmail ? `<a href="mailto:${esc(teacherEmail)}" style="color:#2563eb;text-decoration:none;">${esc(teacherEmail)}</a>` : ''}
  </div>` : '';

  const body = headerStripe + heroStats + ctaBlock + questionTable + contactBlock;
  return emailShell(body, lang);
}

// ── Retake / resend email ─────────────────────────────────────────────────────

function retakeHtml(p: Record<string, unknown>, lang: string) {
  const toName       = String(p.to_name       || p.student_name || '');
  const teacher      = String(p.teacher_name  || '');
  const teacherEmail = String(p.teacher_email || '');
  const examTitle    = String(p.exam_title    || '');
  const institution  = String(p.institution_name || '');
  const link         = String(p.retake_link   || '');
  const accessCode   = String(p.access_code   || '');

  const nameParts = toName.trim().split(/\s+/);
  const firstName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : (nameParts[0] || '');

  const T = lang === "en" ? {
    greeting:    firstName ? `Hello ${esc(firstName)},` : `Hello,`,
    body:        teacher
      ? `Your instructor <strong>${esc(teacher)}</strong> has granted you permission to retake the following exam:`
      : `You have been granted permission to retake the following exam:`,
    btnLabel:        "⬇ Download retake file",
    fallback:        "If the button doesn't work, copy this link:",
    singleUse:       "This link is for single use.",
    accessCodeLabel: "Your access code :",
    contactLabel:    "For any question, contact your instructor :",
  } : {
    greeting:    firstName ? `Bonjour ${esc(firstName)},` : `Bonjour,`,
    body:        teacher
      ? `Votre enseignant <strong>${esc(teacher)}</strong> vous a autorisé(e) à repasser l'examen suivant :`
      : `Vous avez été autorisé(e) à repasser l'examen suivant :`,
    btnLabel:        "⬇ Télécharger le fichier de reprise",
    fallback:        "Si le bouton ne fonctionne pas, copiez ce lien :",
    singleUse:       "Ce lien est à usage unique.",
    accessCodeLabel: "Votre code d'accès :",
    contactLabel:    "Pour toute question, contactez votre enseignant :",
  };

  const content = `
  <div style="background:#fff;padding:36px 32px;border:1px solid #e2e8f0;border-top:none;">
    <h2 style="margin:0 0 6px;font-size:1.1rem;color:#0a0a0a;">${T.greeting}</h2>
    <p style="color:#64748b;font-size:0.9rem;margin:0 0 4px;">${T.body}</p>
    <h3 style="margin:0 0 2px;font-size:1rem;font-weight:700;color:#0f172a;">${esc(examTitle)}</h3>
    ${institution ? `<p style="margin:0 0 20px;font-size:0.78rem;color:#94a3b8;">${esc(institution)}</p>` : '<div style="margin-bottom:20px;"></div>'}
    ${accessCode ? `<p style="font-size:0.8rem;color:#64748b;text-align:center;margin:0 0 6px;">${T.accessCodeLabel}</p>
    <span style="display:block;background:#f1f5f9;padding:12px 16px;font-size:1.1rem;font-weight:700;letter-spacing:0.1em;text-align:center;color:#0f172a;border-radius:0;margin-bottom:24px;">${esc(accessCode)}</span>` : ''}
    <a href="https://dashboard.test-flo.com/retake-seb.html?url=${encodeURIComponent(link.replace('sebs://', 'https://'))}" style="display:inline-block;background:#2563eb;color:#fff;padding:12px 28px;text-decoration:none;font-weight:700;font-size:0.9rem;">${T.btnLabel}</a>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 16px;">
    <p style="font-size:0.8rem;color:#64748b;margin:0;">${T.fallback}<br>
      <span style="color:#2563eb;">${esc(link)}</span>
    </p>
    <p style="font-size:0.75rem;color:#94a3b8;margin:16px 0 0;">${T.singleUse}</p>
    <p style="font-size:0.75rem;color:#94a3b8;margin:8px 0 0;">${lang === 'en' ? 'This link opens automatically in Safe Exam Browser.<br>If it does not open, make sure SEB is installed on your computer.' : 'Ce lien s\'ouvre automatiquement dans Safe Exam Browser.<br>Si le lien ne s\'ouvre pas, assurez-vous que SEB est bien installé sur votre ordinateur.'}</p>
    ${(teacher || teacherEmail) ? `<p style="font-size:0.8rem;color:#64748b;text-align:center;margin:16px 0 0;">${T.contactLabel}<br>${teacher ? `<strong style="color:#1e293b;">${esc(teacher)}</strong>` : ''}${teacher && teacherEmail ? ' — ' : ''}${teacherEmail ? `<a href="mailto:${esc(teacherEmail)}" style="color:#2563eb;text-decoration:none;">${esc(teacherEmail)}</a>` : ''}</p>` : ''}
    <p style="font-size:0.75rem;color:#94a3b8;text-align:center;padding:16px 0 0;">${lang === 'en' ? 'This message was generated automatically by testflo.' : 'Ce message a été généré automatiquement par testflo.'}</p>
  </div>`;

  return emailShell(content, lang);
}

// ── Invite email ──────────────────────────────────────────────────────────────

function inviteHtml(p: Record<string, unknown>, lang: string) {
  const teacher      = String(p.teacher_name  || '');
  const teacherEmail = String(p.teacher_email || '');
  const examTitle    = String(p.exam_title    || '');
  const institution  = String(p.institution_name || '');
  const link         = String(p.exam_link     || '');
  const code         = String(p.access_code   || '');
  const duration     = String(p.duration_mins || '');
  const sebUrl       = p.seb_url ? String(p.seb_url) : null;

  const T = lang === "en" ? {
    greeting:        `Hello,`,
    body:            teacher
      ? `<strong>${esc(teacher)}</strong> has invited you to take the following exam:`
      : `You have been invited to take the following exam:`,
    duration:        `Duration`,
    minutes:         `minutes`,
    btnLabel:        `Start exam →`,
    fallback:        `If the button doesn't work, copy this link:`,
    singleUse:       `This link is for single use.`,
    accessCodeLabel: `Your access code :`,
    contactLabel:    `For any question, contact your instructor :`,
    sebStep1:        `Step 1 — Open the secure browser`,
    sebInstr:        `Click the button below — it will open Safe Exam Browser and load your exam automatically.`,
    sebBtn:          `Start exam →`,
    sebDownload:     `Don't have SEB installed? Download the config file instead.`,
    sebStep2:        `Step 2 — Sign in with your access code`,
  } : {
    greeting:        `Bonjour,`,
    body:            teacher
      ? `<strong>${esc(teacher)}</strong> vous invite à passer l'examen suivant :`
      : `Vous êtes invité(e) à passer l'examen suivant :`,
    duration:        `Durée`,
    minutes:         `minutes`,
    btnLabel:        `Commencer l'épreuve →`,
    fallback:        `Si le bouton ne fonctionne pas, copiez ce lien :`,
    singleUse:       `Ce lien est à usage unique.`,
    accessCodeLabel: `Votre code d'accès :`,
    contactLabel:    `Pour toute question, contactez votre enseignant :`,
    sebStep1:        `Étape 1 — Ouvrir le navigateur sécurisé`,
    sebInstr:        `Cliquez sur le bouton ci-dessous — Safe Exam Browser s'ouvrira et chargera votre examen automatiquement.`,
    sebBtn:          `Commencer l'épreuve →`,
    sebDownload:     `SEB non installé ? Téléchargez le fichier de configuration.`,
    sebStep2:        `Étape 2 — Connectez-vous avec votre code d'accès`,
  };

  const content = `
  <div style="background:#fff;padding:36px 32px;border:1px solid #e2e8f0;border-top:none;">
    <h2 style="margin:0 0 6px;font-size:1.1rem;color:#0a0a0a;">${T.greeting}</h2>
    <p style="color:#64748b;font-size:0.9rem;margin:0 0 4px;">${T.body}</p>
    <h3 style="margin:0 0 2px;font-size:1rem;font-weight:700;color:#0f172a;">${esc(examTitle)}</h3>
    ${institution ? `<p style="margin:0 0 20px;font-size:0.78rem;color:#94a3b8;">${esc(institution)}</p>` : '<div style="margin-bottom:20px;"></div>'}
    ${duration ? `<p style="margin:0 0 12px;font-size:0.85rem;color:#475569;"><strong>${T.duration}:</strong> ${esc(duration)} ${T.minutes}</p>` : ''}
    ${code ? `<p style="font-size:0.8rem;color:#64748b;text-align:center;margin:0 0 6px;">${T.accessCodeLabel}</p>
    <span style="display:block;background:#f1f5f9;padding:12px 16px;font-size:1.1rem;font-weight:700;letter-spacing:0.1em;text-align:center;color:#0f172a;border-radius:0;margin-bottom:24px;">${esc(code)}</span>` : ''}
    ${sebUrl ? `<p style="margin:0 0 4px;font-size:0.72rem;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#64748b;">${T.sebStep1}</p>
    <p style="margin:0 0 10px;font-size:0.82rem;color:#475569;">${T.sebInstr}</p>
    <a href="https://dashboard.test-flo.com/launch-seb.html?url=${encodeURIComponent(sebUrl)}" style="display:inline-block;background:#2563eb;color:#fff;padding:10px 24px;text-decoration:none;font-weight:700;font-size:0.85rem;margin-bottom:8px;">${T.sebBtn}</a>
    <p style="margin:0 0 4px;font-size:0.75rem;color:#94a3b8;"><a href="${esc(sebUrl)}" download style="color:#94a3b8;">${T.sebDownload}</a></p>
    ` : `<a href="${esc(link)}" style="display:inline-block;background:#2563eb;color:#fff;padding:12px 28px;text-decoration:none;font-weight:700;font-size:0.9rem;">${T.btnLabel}</a>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 16px;">
    <p style="font-size:0.8rem;color:#64748b;margin:0;">${T.fallback}<br>
      <span style="color:#2563eb;">${esc(link)}</span>
    </p>`}
    ${(teacher || teacherEmail) ? `<p style="font-size:0.8rem;color:#64748b;text-align:center;margin:16px 0 0;">${T.contactLabel}<br>${teacher ? `<strong style="color:#1e293b;">${esc(teacher)}</strong>` : ''}${teacher && teacherEmail ? ' — ' : ''}${teacherEmail ? `<a href="mailto:${esc(teacherEmail)}" style="color:#2563eb;text-decoration:none;">${esc(teacherEmail)}</a>` : ''}</p>` : ''}
    <p style="font-size:0.75rem;color:#94a3b8;text-align:center;padding:16px 0 0;">${lang === 'en' ? 'This message was generated automatically by testflo.' : 'Ce message a été généré automatiquement par testflo.'}</p>
  </div>`;

  return emailShell(content, lang);
}

// ── Ticket notification email ─────────────────────────────────────────────────

function ticketHtml(p: Record<string, string>): string {
  const studentRow = p.student_email
    ? `<tr><td style="padding:8px 0;font-size:0.82rem;color:#94a3b8;width:130px;">Student</td><td style="padding:8px 0;font-size:0.82rem;color:#0f172a;">${esc(p.student_email)}</td></tr>`
    : '';
  const content = `
  <div style="background:#fff;padding:32px;border:1px solid #e2e8f0;border-top:none;">
    <p style="margin:0 0 6px;font-size:0.65rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#94a3b8;">Support Ticket</p>
    <h2 style="margin:0 0 24px;font-size:1.1rem;font-weight:700;color:#0f172a;">${esc(p.category || 'Issue reported')}</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
      <tr><td style="padding:8px 0;font-size:0.82rem;color:#94a3b8;width:130px;">From</td><td style="padding:8px 0;font-size:0.82rem;color:#0f172a;font-weight:600;">${esc(p.teacher_name || '—')}</td></tr>
      <tr><td style="padding:8px 0;font-size:0.82rem;color:#94a3b8;">Email</td><td style="padding:8px 0;font-size:0.82rem;"><a href="mailto:${esc(p.teacher_email || '')}" style="color:#2563eb;text-decoration:none;">${esc(p.teacher_email || '—')}</a></td></tr>
      ${studentRow}
      <tr><td style="padding:8px 0;font-size:0.82rem;color:#94a3b8;">Submitted</td><td style="padding:8px 0;font-size:0.82rem;color:#94a3b8;">${esc(p.submitted_at || '')}</td></tr>
    </table>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:4px;padding:16px 20px;">
      <p style="margin:0 0 6px;font-size:0.65rem;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#94a3b8;">Description</p>
      <p style="margin:0;font-size:0.88rem;color:#0f172a;line-height:1.7;white-space:pre-wrap;">${esc(p.description || '—')}</p>
    </div>
  </div>`;
  return emailShell(content, "en");
}

// ── HTML escape ───────────────────────────────────────────────────────────────

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
