import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// Service role key — never exposed to the client, server-side only
const SUPABASE_URL  = Deno.env.get("SUPABASE_URL")              ?? "";
const SERVICE_KEY   = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function respond(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });
}

async function dbGet(path: string) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    headers: {
      "apikey":         SERVICE_KEY,
      "Authorization":  `Bearer ${SERVICE_KEY}`,
      "Content-Type":   "application/json",
    },
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, data: text ? JSON.parse(text) : null };
}

async function dbPost(path: string, body: unknown) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    method: "POST",
    headers: {
      "apikey":         SERVICE_KEY,
      "Authorization":  `Bearer ${SERVICE_KEY}`,
      "Content-Type":   "application/json",
      "Prefer":         "return=representation",
    },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, data: text ? JSON.parse(text) : null };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });
  if (req.method !== "POST") return respond({ error: "Method not allowed" }, 405);

  try {
    const { share_id, access_code, student_name, student_email, group_name, shuffle_map } =
      await req.json();

    if (!share_id) {
      return respond({ error: "Missing required fields" }, 400);
    }

    // ── 0. Metadata-only mode — boot() pre-login fetch ───────────────────────
    // Called with only share_id to populate the login screen before the student
    // enters their details. Returns public info only — no attempt is created.
    if (!access_code && !student_name && !student_email) {
      const metaRes = await dbGet(
        `exams?share_id=eq.${encodeURIComponent(share_id)}&status=eq.published` +
        `&select=title,duration_mins,lang,groups,instructions&limit=1`
      );
      if (!metaRes.ok || !metaRes.data || metaRes.data.length === 0) {
        return respond({ error: "Exam not found or not published" }, 404);
      }
      const meta = metaRes.data[0];
      return respond({
        title:         meta.title          ?? "",
        duration_mins: meta.duration_mins  ?? 0,
        lang:          meta.lang           ?? "fr",
        groups:        meta.groups         ?? null,
        instructions:  meta.instructions   ?? null,
      });
    }

    // ── Full-start mode — requires all login fields ───────────────────────────
    if (!access_code || !student_name || !student_email) {
      return respond({ error: "Missing required fields" }, 400);
    }

    // ── 1. Fetch exam (service role — client never sees this query) ──────────
    const examRes = await dbGet(
      `exams?share_id=eq.${encodeURIComponent(share_id)}&status=eq.published` +
      `&select=id,title,duration_mins,access_code,group_codes,groups,lang,instructions&limit=1`
    );

    if (!examRes.ok || !examRes.data || examRes.data.length === 0) {
      return respond({ error: "Exam not found or not published" }, 404);
    }

    const exam = examRes.data[0];

    // ── 2. Validate access code server-side ──────────────────────────────────
    let groupCodes: Record<string, string> | null = null;
    try {
      if (exam.group_codes) {
        groupCodes = typeof exam.group_codes === "string"
          ? JSON.parse(exam.group_codes)
          : exam.group_codes;
      }
    } catch (_) { groupCodes = null; }

    let codeMatch = false;
    if (group_name && groupCodes && groupCodes[group_name]) {
      codeMatch = String(groupCodes[group_name]).trim().toLowerCase() ===
                  String(access_code).trim().toLowerCase();
    } else {
      codeMatch = String(exam.access_code ?? "").trim().toLowerCase() ===
                  String(access_code).trim().toLowerCase();
    }

    if (!codeMatch) {
      return respond({ error: "Invalid access code" }, 401);
    }

    // ── 2.5. Block duplicate sessions — one active attempt per email per exam ──
    const normEmail = String(student_email).trim().toLowerCase();
    const activeCheck = await dbGet(
      `exam_attempts?exam_id=eq.${encodeURIComponent(exam.id)}` +
      `&student_email=eq.${encodeURIComponent(normEmail)}` +
      `&status=eq.in_progress&select=id&limit=1`
    );
    if (activeCheck.ok && activeCheck.data && activeCheck.data.length > 0) {
      return respond({ error: "active_session_exists" }, 409);
    }

    // ── 3. Create attempt — session_token auto-generated by DB default ────────
    const attemptRes = await dbPost(
      "exam_attempts?select=id,session_token",
      {
        exam_id:      exam.id,
        student_name: String(student_name).trim(),
        student_email: normEmail,
        access_code:  String(access_code).trim(),
        group_name:   group_name || null,
        status:       "in_progress",
        shuffle_map:  shuffle_map || null,
      }
    );

    if (!attemptRes.ok || !attemptRes.data || attemptRes.data.length === 0) {
      console.error("exam-start: attempt insert failed", attemptRes.status, JSON.stringify(attemptRes.data));
      return respond({ error: "Failed to create attempt" }, 500);
    }

    const attempt = attemptRes.data[0];

    // ── 4. Return only what the client needs ─────────────────────────────────
    // Never return: correct_index, access_code, teacher_email, or service key
    return respond({
      attempt_id:    attempt.id,
      session_token: attempt.session_token,
      exam_id:       exam.id,
      duration_mins: exam.duration_mins,
      lang:          exam.lang          ?? "fr",
      title:         exam.title         ?? "",
      instructions:  exam.instructions  ?? null,
    });

  } catch (e) {
    console.error("exam-start unhandled error:", String(e));
    return respond({ error: "Internal server error" }, 500);
  }
});
